### PR TITLE
Resource Stats

### PR DESCRIPTION
**Pull request by MRossol**
Class to compute temporal stats efficiently

TODO: create CLI

### CODE REVIEW

**Comment by grantbuster** [comment]
@MRossol this looks cool! My only comment is that there is a lot of overlap in the method names. I understand some are class methods and some are instance methods but for anyone external using this from ipython or jupyter I dont think it will be obvious where to start. If you're really keen on keeping the copies then I think it all looks good. 

`_compute_stats() _extract_stats() compute_statistics() all_stats() statistics()`
`annual() annual_stats()`
`diurnal() diurnal_stats()`
`monthly() monthly_stats()`
`monthly_diurnal() monthly_diurnal_stats()`

**Comment by grantbuster** [comment]
@MRossol this is minor but could you also add SLURM imported on the top level? I keep trying to do "from rex import SLURM" and i keep meaning to include that in the next rex PR

**Comment by MRossol** [comment]
Re: names

The hidden methods were a necessary evil due to the complexity of the code, figure that was better than during off flake8 warnings

In terms of the methods vs class methods I agree they are redundant and a bit repetitive but I wanted to make it easier for the noob to pull stats vs. having to understand the nuance of this method:
https://github.com/NREL/rex/blob/3f2f1c9feb82215ebf2b077355fe36d4d2b6ac1a/rex/resource_extraction/resource_stats.py#L431

Open to suggestions for making it clearer while also accessible... 

Added SLURM to the top __init__

**Comment by grantbuster** [comment]
Would you want to just make the instance methods protected with an underscore?

**Review by grantbuster — APPROVED** [review]

**Comment by MRossol** [comment]
I actually want the instance methods to be exposed along with the class methods. Again for the lamen who just wants one of the above types of stats

**Pull request merged**
