### PR TITLE
add US Wave CLI

### PR DESCRIPTION
**Pull request by MRossol**
clean up multi year means maps and other CLI option order

### CODE REVIEW

**Comment by grantbuster** [comment]
@MRossol do you want to try setting h5py >= 3.1.0?

released recently:
https://pypi.org/project/h5py/3.1.0/

**Comment by MRossol** [comment]
Have they released 3.1? I pushed that up when 3.0 was the latest

**Comment by MRossol** [comment]
Add check for lat, lon coords against min/max lat, lons from resource meta

**Comment by lkilcher** [comment]
@MRossol, sorry it took me so long to get here. It looks like I've missed most of the action (i.e., PR merged)? I looked through the `US_wave_cli.py` file briefly. It looks great to me. Thanks!

**Pull request merged**
