### PR TITLE
Format to SAM csv

### PR DESCRIPTION
**Pull request by MRossol**
Update SAM df with year, month, day, hour instead of time-index
Rename columns

### CODE REVIEW

**Comment by MRossol** [comment]
Request from an external user, not sure its fully SAM compatible but closer...
Will pull a file tomorrow on Eagle as a test of the new csv reformating
Tests updated with new variable names

**Comment by MRossol** [comment]
Fixed a bug, here is the new output from the CLI:

[SAM-323183.csv.zip](https://github.com/NREL/rex/files/4623282/SAM-323183.csv.zip)

**Comment by grantbuster** [comment]
@MRossol, this is great! We need to add the minute column for the NSRDB data to be SAM-compatible. Maybe: `if len(df) > 8784: add_minute_col()`

Also, what would happen with a leap year?

**Comment by MRossol** [comment]
Good call! I'll do that now. 

That is a good question. I'll ask Darice, I assumed SAM would handle it....

**Comment by grantbuster** [comment]
Mind sending me a new csv for 2018 and maybe 2012 too? I can test it. 

I feel like SAM will reject anything that is `not len % 8760 == 0`

@mikebannis had to deal with this for the solar thermal stuff. If i remember correctly, SAM always wanted the "normal" time index without the leap day. The question is whether we want to handle that in the rex code or let the users make their own leap day assumptions.

**Comment by MRossol** [comment]
updated 2018 5min file is 32313
2012 30min file is 592127
[SAM.zip](https://github.com/NREL/rex/files/4623665/SAM.zip)

**Comment by grantbuster** [comment]
@MRossol, both files run in SAM pvwatts. The 2012 data output does not have Feb 29th, i assume all those timesteps got removed. I think this is fine for rex. We should provide all the data possible in a format that will run and then the user can decide to make their own assumptions from there.

**Pull request merged**
