### PR TITLE
Gb/fun utils

### PR DESCRIPTION
**Pull request by grantbuster**

### CODE REVIEW

**Review by bnb32 — DISMISSED** [review]
This is awesome dude! I love the generality. This will be so useful.

**Review by ppinchuk — APPROVED** [review]
I don't fully understand the use case for these functions, but I assume its something more than can be done with [Signature.bind()](https://docs.python.org/3/library/inspect.html#inspect.Signature.bind)  in conjunction with [Signature.parameters](https://docs.python.org/3/library/inspect.html#inspect.Signature.parameters).

Generally, this looks very good, nice job @grantbuster!
I am especially a fan of adopting the `f-string` syntax over `.format()`.
Also, really nice job with the tests.

One super minor point is that the docstrings for the smaller helper functions `(arg_to_str, has_class, get_class, is_standalone_fun, is_instance_method)` are rather barebones. I understand that they are quick utility functions, but if they are meant for use by others, it may be worthwhile to flesh out the documentation instead of making the users go to source code. (If they are not means for use by others, we should consider making them protected). Not a big deal here though - I'm definitely not trying to be a stickler so I'm approving these changes 😄

**Comment by grantbuster** [comment]
Yeah you would think so, but the bind method is a bit opaque and i really cant tell whether its actually useful or not... See the example screenshot below. I think parsing our args/kwargs manually is probably best for more flexible use cases. 

Yeah the fstring thing is nice but some habits die hard haha. I still think the .format() is nice just for readability sometimes. 

Finally yeah, I can add some detail to the docstrings, you're probably right that this is probably worth expanding on since its kind of a funky module. 

image

**Comment by ppinchuk** [comment]
Yea, fair enough. I don't think you can get away with `bind` unless you couple it with `sig.parameters`, but if you want finer control anyway, what you have is probably better 
image

**Comment by grantbuster** [comment]
yeah sorry, we want to be able to build a CLI for a python module by putting the following in a sbatch script, but in order to do so we need to be able to programmatically parse the `arg_str` from the function signature and a generic config dictionary. It's a more simple approach than the reV CLI's which have special config objects. I'd rather the config map directly to class methods. 

```
        cmd = ("python -c '{import_str};{f}({a})'"
               .format(import_str=import_str, f=fun_str, a=arg_str))

        out = slurm_manager.sbatch(cmd,

**Comment by ppinchuk** [comment]
Ah gotcha gotcha. Yea, if you ultimately need the function call formatted as a string, then your methods are totally the way to go!

**Review by ppinchuk — APPROVED** [review]
LGTM

**Pull request merged**
