### PR TITLE
used median to check for units, more accurate than min or max for sim…

### PR DESCRIPTION
**Pull request by grantbuster**
…ulated or bad data

### CODE REVIEW

**Comment by MRossol** [comment]
Why is median more accurate? I'd be afraid of outliers being outside the allowable SAM range in we use median. Min/Max seem much stricter...

**Comment by grantbuster** [comment]
This is purely for recognition/identification of the units. So the median gives a good idea of what the middle-of-the-road data looks like. Consider a bad dataset where you have pressure in the nominal Pascal range but then one or two timesteps didn't get written so they have values of zero. You would want to identify the Pascal unit using the median, not the min value (which would represent a single corrupted value).

**Comment by MRossol** [comment]
Gotcha, that makes sense. Do we want to do another minor release for this?

**Comment by grantbuster** [comment]
@MRossol, yeah might as well since you just patched a bug too right? And this unit recognition thing caused issues for me once upon a time I think. We can update the reV requirements as well.

**Pull request merged**
